language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

env:
  - DJANGO_VERSION=1.8

install:
  - pip install -e .
  - pip install Django==$DJANGO_VERSION coveralls==1.2.0 tabulate==0.7.5 coverage==4.4.1 pytest==3.2.3 pytest-cov==2.5.1 pytest-django==3.1.2 pytest-runner==2.12.1 pytest-sugar==0.9.0 tox==2.9.1

script:
  - pytest

after_success:
  - coveralls
