language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

notifications:
  email: false

env:
  - DJANGO_VERSION=1.8.14

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install tabulate
  - pip install coveralls
  - pip install tox
  - pip install Jinja2
  - python setup.py -q install

script:
  - tox

after_success:
  - coveralls
