language: python

python:
  - "2.7"
  - "3.5"

env:
  - REQUIREMENTS=demo/requirements/requirements-1.8.txt

install:
  - pip install .
  - pip install -r $REQUIREMENTS

script:
  - tox

after_success:
  - coveralls
