language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

env:
  - DJANGO_VERSION=1.8

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .[test]

script:
  - pytest

after_success:
  - coveralls
