sudo: false
language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env: DJANGO="Django>=1.8,<1.9"
    - python: 3.4
      env: DJANGO="Django>=1.8,<1.9"
    - python: 3.5
      env: DJANGO="Django>=1.8,<1.9"

    - python: 2.7
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.4
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.5
      env: DJANGO="Django>=1.9,<1.10"

    - python: 2.7
      env: DJANGO="Django>=1.10,<1.11"
    - python: 3.4
      env: DJANGO="Django>=1.10,<1.11"
    - python: 3.5
      env: DJANGO="Django>=1.10,<1.11"

    - python: 2.7
      env: DJANGO="Django>=1.11,<2.0"
    - python: 3.4
      env: DJANGO="Django>=1.11,<2.0"
    - python: 3.5
      env: DJANGO="Django>=1.11,<2.0"
    - python: 3.6
      env: DJANGO="Django>=1.11,<2.0"

before_install:
    - pip install sphinx flake8
    - flake8
    - sphinx-build -b html docs docs/_build

install:
    - pip install -e .[test]
    - pip install -U $DJANGO

script:
    - pytest --cov=unload

after_success:
    - coveralls


notifications:
    email: false
